### ISSUE TITLE
Bugs found while running tutorial

### ISSUE THREAD

**Issue by DSilva27** [flatironinstitute/cryoSBI#59]
These are two very minor bugs

1. umap is not listed as a dependency in the pyproject.toml. It should either be added there, or it should be written in the README that the user needs to install it.

2. Second to last cell of the tutorial, there is a variable that does not exist (`dist`), but is required to do one of the plots.

**Comment by Dingel321** [comment]
Fixed bug. I didn't add UMAP as a requirement since it is just one possible way to analyse latent space. I mentioned it in the readme during the part of UMAP analysis and also added installation instructions in the tutorial
